baseURL = 'http://jkmackie.github.io/'
languageCode = 'en-us'
#Use three single quotes for literal string that goes multi-line
title = '''Justin Mackie'''
theme = 'ezhil'

[params]
    mode = "dark"
    subtitle = "I extract value from data using machine learning techniques."    

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3